//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMeThatApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMeThatTable
    {
        public string SendersEmail { get; set; }
        public string ReceiversEmail { get; set; }
        public System.DateTime SharedDate { get; set; }
        public string SharedCode { get; set; }
        public int SNo { get; set; }
    }
}
